### ISSUE TITLE
Cannot shutdown with staging updates; reboots regardless

### ISSUE THREAD

**Issue by teamcons** [elementary/quick-settings#67]
### What Happened?

When there are downloaded updates, i do want to have them installed - but i am done with the computer
so i let the tick "install updates on", but click on shutdown.
i see the system installing pending updates... but am greeting later my desktop, requiring a manual intervention to shutdown

### Steps to Reproduce

-have system updates
-click shutdown
-it does the update... and reboots

### Expected Behavior

updates are installed, then the OS shuts down as initially requested

### OS Version

8.x (Early Access)

### Session Type

Secure Session (Wayland)

### Software Version

Latest release (I have run all updates)

**Comment by leolost2605** [comment]
This is because of this line
https://github.com/elementary/quick-settings/blob/bff204ae943eddae7a2d0ba9ee122aac48dec070/src/Widgets/EndSessionDialog.vala#L127

If shutdown is clicked we set the action to POWER_OFF but then emit reboot () which will override the action again to REBOOT.

I'll propose a PR later today or tomorrow just noting it down so that I don't forget it or if somebody else wants to do it in the meantime 🤷

**Comment by teamcons** [comment]
The bug is still present. Can we reopen this please?

**Comment by danirabbit** [comment]
@teamcons are you testing with daily or building from git main? There hasn't been a release since this was fixed in December so you'll still see it on stable, but it should be fixed in daily
